version: "3.7"
services:
  nn_backend:
    image: pocketfoundation/node-nanny:latest
    container_name: nn_backend
    ports:
      - "4000:4000"
    hostname: nn_backend
    depends_on:
      - nn_db
      - nn_redis
    environment:
      REDIS_HOST: nn_redis
      BACKEND_HOST: nn_backend
      FRONTEND_HOST: nn_frontend
      PORT: "3000"
      API_PORT: "4000"

      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID:?Discord Server ID not set.}
      DISCORD_TOKEN: ${DISCORD_TOKEN:?Discord token not set.}

      MONGO_URI: "mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-rootpassword}@nn_db:27017/${MONGO_DB_NAME:-local}?authSource=admin"
      ALERT_TRIGGER_THRESHOLD: ${ALERT_TRIGGER_THRESHOLD:-6}
      ALERT_RETRIGGER_THRESHOLD: ${ALERT_RETRIGGER_THRESHOLD:-20}
      MONITOR_LOGGER: ${MONITOR_LOGGER:-mongodb}

  nn_frontend:
    image: pocketfoundation/node-nanny-ui:latest
    container_name: nn_frontend
    ports:
      - "3000:3000"
    hostname: nn_frontend
    environment:
      REDIS_HOST: nn_redis
      BACKEND_HOST: nn_backend
      FRONTEND_HOST: nn_frontend
      PORT: "3000"
      API_PORT: "4000"

  nn_db:
    image: mongo:latest
    container_name: nn_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-rootpassword}
    volumes:
      - ${MONGO_DB_PATH:-~/data/db}:/data/db
    ports:
      - "27017:27017"

  nn_redis:
    image: "redis:latest"
    container_name: nn_redis
