version: "3.7"
services:
  nn_stack:
    image: pocketfoundation/node-nanny
    container_name: nn_stack
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - nn_db
      - nn_redis
    environment:
      MONITOR_TEST: ${MONITOR_TEST}
      MONITOR_LOGGER: ${MONITOR_LOGGER:-mongodb}
      MONGO_URI: "mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-rootpassword}@nn_db:27017/${MONGO_DB_NAME:-local}?authSource=admin"
      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID:?Discord Server ID not set.}
      DISCORD_TOKEN: ${DISCORD_TOKEN:?Discord token not set.}
      REDIS_HOST: nn_redis

  nn_db:
    image: mongo:latest
    container_name: nn_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-rootpassword}
    volumes:
      - mongodb_data_container:/data/db

  nn_redis:
    image: "redis:latest"
    container_name: nn_redis

volumes:
  mongodb_data_container:
