version: "3.7"
services:
  nn_stack:
    image: nodejs
    container_name: nn_stack
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - nn_db
      - nn_redis
    environment:
      DOCKER: "true"
      MONITOR_TEST: "1"
      MONGO_URI: "mongodb://root:rootpassword@nn_db:27017/local?authSource=admin"
      DISCORD_SERVER_ID: "948015924005462036"
      DISCORD_TOKEN: "OTQ4NzE0NDY1MDUzMDEyMDEw.Yh_1Mg.Fvgd9qZpQ2s0w5Rcdk1DDt7DvlE"

  nn_db:
    container_name: nn_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  nn_redis:
    container_name: nn_redis
    image: "redis:latest"

volumes:
  mongodb_data_container:
