version: "3.7"
services:
  nn_stack:
    image: ubuntu:20.04
    container_name: nn_stack
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - nn_db
      - nn_redis
    environment:
      MONITOR_TEST: ${MONITOR_TEST}
      MONITOR_LOGGER: ${MONITOR_LOGGER}
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@nn_db:27017/${MONGO_DB_NAME}?authSource=admin"
      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DD_API_KEY: ${DD_API_KEY}

  nn_db:
    container_name: nn_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  nn_redis:
    container_name: nn_redis
    image: "redis:latest"

volumes:
  mongodb_data_container:
