version: "3.7"
services:
  nn_backend:
    image: pocketfoundation/node-nanny:latest
    container_name: nn_backend
    ports:
      - "4000:4000"
    hostname: nn_backend
    depends_on:
      - nn_db
      - nn_redis
    environment:
      # Hardcoded Docker Compose vars
      REDIS_HOST: nn_redis

      # Required Environment Variables
      DISCORD_SERVER_ID: ${DISCORD_SERVER_ID:?Discord Server ID not set.}
      DISCORD_TOKEN: ${DISCORD_TOKEN:?Discord token not set.}

      # Optional Environment Variables
      ALERT_TRIGGER_THRESHOLD: ${ALERT_TRIGGER_THRESHOLD:-6}
      ALERT_RETRIGGER_THRESHOLD: ${ALERT_RETRIGGER_THRESHOLD:-20}
      MONITOR_LOGGER: ${MONITOR_LOGGER:-mongodb}

      MONGO_URI: "mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-rootpassword}@nn_db:27017/${MONGO_DB_NAME:-local}?authSource=admin"

      # PNF INTERNAL ONLY
      PNF: "1"
      PNF_DISPATCH_THRESHOLD: "5"
      DD_API_KEY: ${DD_API_KEY}
      PAGER_DUTY_API_KEY: ${PAGER_DUTY_API_KEY}

  nn_frontend:
    image: pocketfoundation/node-nanny-ui:latest
    container_name: nn_frontend
    ports:
      - "3000:3000"
    hostname: nn_frontend
    depends_on:
      - nn_backend
      - nn_db
      - nn_redis

  nn_db:
    image: mongo:latest
    container_name: nn_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-local}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-rootpassword}
    volumes:
      - ~/data/db:/data/db
    ports:
      - "27017:27017"

  nn_redis:
    image: "redis:latest"
    container_name: nn_redis
