name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    name: Docker build & push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: pocketfoundation/node-nanny
          tag-custom: latest
          tag-semver: |
            {{raw}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
