name: CI

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  build-test:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Test
        env:
          TEST_DISCORD_SERVER_ID: ${{ secrets.TEST_DISCORD_SERVER_ID }}
          TEST_DISCORD_TOKEN: ${{ secrets.TEST_DISCORD_TOKEN }}
        run: pnpm test
